ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: dbt_local
      host: trino
      port: 8084
      database: delta
      schema: default
      threads: 4
