ALTER TABLE products ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE stocks ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE orders ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE order_items ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE warehouses ADD COLUMN version BIGINT DEFAULT 0;
ALTER TABLE users ADD COLUMN version BIGINT DEFAULT 0;