spring:
  application:
    name: ecommerce-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:1900/ecommerce
    user: user
    password: password
    locations: classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

# Application custom properties
app:
  inventory:
    reservation-timeout-minutes: 15
    default-warehouse-id: 00000000-0000-0000-0000-000000000001
  order:
    max-items-per-order: 50

  jwt:
    secret: mySecretKeyThatIsAtLeast32CharactersLong
    expirationMs: 86400000  # 24 ore

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
